# Generated by Django 3.1 on 2020-08-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_watchlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='items',
            field=models.ManyToManyField(related_name='items', to='auctions.listing'),
        ),
    ]
