# Generated by Django 3.1 on 2020-08-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200827_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bids',
            field=models.OneToOneField(default=30, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.bidding'),
            preserve_default=False,
        ),
    ]
