# Generated by Django 3.1 on 2020-08-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200827_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ManyToManyField(null=True, related_name='product', to='auctions.listing'),
        ),
    ]
