# Generated by Django 3.1 on 2020-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com',
            field=models.CharField(default='', max_length=300),
        ),
    ]
