# Generated by Django 3.1 on 2020-08-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200827_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
