# Generated by Django 3.1 on 2020-08-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_bidding_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='starting',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='auctions.user'),
            preserve_default=False,
        ),
    ]
