# Generated by Django 3.1 on 2020-08-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20200828_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='starting',
        ),
    ]
