# Generated by Django 3.1 on 2020-08-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_remove_bidding_starting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='start',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
