# Generated by Django 3.1 on 2020-08-31 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20200831_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='money',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money', to=settings.AUTH_USER_MODEL),
        ),
    ]
